### ISSUE TITLE
作者用最新脚本能挖到了吗

### ISSUE THREAD

**Issue by dsa169** [Cloxl/noss-python#2]
作者用最新脚本能挖到了吗

**Comment by Cloxl** [comment]
买的起代理ip 和 弄个好一点的arb节点才能玩

**Comment by dsa169** [comment]
作者，你推特多少，我可以关注你吗

**Comment by Cloxl** [comment]
> 作者，你推特多少，我可以关注你吗

我推特被封了 hhh 没绑手机号码 没啥事我close了哈
